env:
  browser: true
  es2021: true
extends:
  - 'airbnb'
  - 'airbnb-typescript'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: './tsconfig.json'
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'prettier'
rules:
  no-console: 0
  comma-dangle: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  prettier/prettier: ['error', { endOfLine: 'auto' }]
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension: [1, { extensions: ['.jsx', '.tsx'] }]
  '@typescript-eslint/ban-types': 0
  '@typescript-eslint/ban-ts-comment': 0
